import type { Metadata } from 'next';
import '@/utils/styles/globals.scss';
import styles from '@/utils/styles/layout.module.scss';
import Navigation from '@/component/nav/Navigation';

export const metadata: Metadata = {
	title: 'kim-taewan',
	// description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ko">
			<head>
				<title>Wiki</title>
			</head>

			<body className={styles.container}>
				<Navigation />
				{children}
			</body>
		</html>
	);
}
